apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-backend
  labels:
    app: {{ .Values.name }}-backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}-backend
